# Generated by Django 4.1 on 2022-08-16 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_room_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='booking_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('floor', models.IntegerField()),
                ('rating', models.DecimalField(decimal_places=0, max_digits=5)),
                ('review', models.CharField(max_length=200)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Room', to='room.room')),
            ],
        ),
    ]
