# Generated by Django 4.1 on 2022-08-16 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_alter_room_booking_date_alter_room_room_number_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='bad_required',
            field=models.IntegerField(null=True),
        ),
    ]
