# Generated by Django 4.1 on 2022-08-16 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_room_bad_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
