# Generated by Django 4.1 on 2022-08-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_room_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='address',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
