# Generated by Django 4.1 on 2022-08-17 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0006_hotel_address_room_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='bad_required',
            new_name='bad_count',
        ),
    ]
