# Generated by Django 4.1 on 2022-08-17 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0007_rename_bad_required_room_bad_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
