# Generated by Django 4.1 on 2022-08-17 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0008_alter_room_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='date',
            new_name='checkout_date',
        ),
    ]
