# Generated by Django 4.1 on 2022-08-16 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_admin_user_is_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Is_admin',
            new_name='admin',
        ),
    ]
